### ISSUE TITLE
lemke_howson not working properly...

### ISSUE THREAD

**Issue by HLiuUS** [drvinceknight/Nashpy#35]
I have:
3 x 3 Payoff matrix A:
  -1  -1      -1
   0   0       0
  -1  -1  -10000

3 x 3 Payoff matrix B:
  -1  -1      -1
   0   0       0
  -1  -1  -10000

The output is:

>>> eqs = test.lemke_howson(initial_dropped_label=0)
>>> list(eqs)
[array([0, 0]), array([ 0.33445946,  0.33445946,  0.33445946, -0.00337838])]

**Comment by drvinceknight** [comment]
Thanks for raising this @HLiuUS, I will investigate. The game is pretty degenerate so that might be causing some trouble although the mixup in the dimensions seems to indicate an issue that's fixable. On easy improvement of current behaviour would be to at least raise an error if the dimensions aren't correct (for all algorithms)...

It might be a little while before I look at this (a lot of marking/grading this time of year) but I will. Thanks again for taking the time to open the issue :+1:

For my own records:

```python
>>> A = [[-1, -1, -1], [0, 0, 0], [-1, -1, -10000]]
>>> B = A
>>> game = nash.Game(A, B)
>>> list(game.support_enumeration())
[(array([ 0.,  1.,  0.]), array([ 1.,  0.,  0.])),
 (array([ 0.,  1.,  0.]), array([ 0.,  1.,  0.])),
 (array([ 0.,  1.,  0.]), array([ 0.,  0.,  1.]))]
>>> list(game.vertex_enumeration())
[(array([ 0.,  1.,  0.]), array([ 0.,  0.,  1.])),
 (array([ 0.,  1.,  0.]), array([ 0.,  1.,  0.])),
 (array([ 0.,  1.,  0.]), array([ 1.,  0.,  0.]))]
>>> list(game.lemke_howson(0))
[array([ nan,  nan]),
 array([  3.33344446e-01,   3.33344446e-01,   3.33344446e-01,
         -3.33377784e-05])]
```

**Comment by HLiuUS** [comment]
Thanks for the quick feedback VInce, no rush :) 

Just want to let you know that the support_enumeration method works just fine.

**Comment by drvinceknight** [comment]
Thanks again for raising this @HLiuUS, I'm about to merge #36 which adds a warning when the output is nonsensical (as in the case you've sent here). 

So now the output would look like: 

```
/home/vince/src/Nashpy/src/nash/integer_pivoting/integer_pivoting.py:27: RuntimeWarning: invalid value encountered in true_divide
  return np.argmax(tableau[:, column_index] / tableau[:, -1])
/home/vince/src/Nashpy/src/nash/algorithms/lemke_howson.py:54: RuntimeWarning: invalid value encountered in true_divide
  return strategy / sum(strategy)
/home/vince/src/Nashpy/src/nash/algorithms/lemke_howson.py:113: RuntimeWarning: The Lemke Howson algorithm has returned probability vectors of 
incorrect shapes. This indicates an error. Your game could be degenerate.
  warnings.warn(msg, RuntimeWarning)
```

You can see many errors occur along the way because of the fact that the game is degenerate, the final error is the one I've added.

I am contemplating letting the algorithm fail all together but will just use warning for now.
