### ISSUE TITLE
Unexpected behavior - no equilibrium for a simple game

### ISSUE THREAD

**Issue by omerbp** [drvinceknight/Nashpy#39]
Hi,

I discovered that support_enumeration fails to find a mixed NE for the following game (the list is empty). Is it a well known issue?
`
import nash
import numpy as np
M = [[ 0., 1., -0., -1.],
     [-1., 0.,  1.,  1.],
     [ 0., -1.,  0.,  1.],
     [ 1., -1., -1.,  0.]]

rps = nash.Game(M)
print(rps)
eqs = list(rps.support_enumeration())
print(eqs)
`

**Comment by drvinceknight** [comment]
Hi @omerbp yup, that's expected behaviour, the game you've got there is degenerate: the row player's 2nd and 3rd strategies are both best responses to the final strategy. The support enumeration algorithm implemented here is specifically for non degenerate games so it only considers supports of the same size: https://nashpy.readthedocs.io/en/stable/reference/support-enumeration.html?highlight=degenerate

This is to reduce inefficiency of checking all potential supports.

**Comment by drvinceknight** [comment]
@omerbp for your information I have updated the library (the latest release is version 0.0.16) and it now support enumeration handles degeneracy in a hopefully more understandable way. This is the behaviour with your game:

```python
>>> import nashpy as nash
>>> import numpy as np
>>> M = [[ 0., 1., -0., -1.],
...            [-1., 0., 1., 1.],
...            [ 0., -1., 0., 1.],
...            [ 1., -1., -1., 0.]]
>>> game = nash.Game(M)
>>> list(game.support_enumeration())
[(array([  3.33333333e-01,   3.33333333e-01,   2.77555756e-17,
           3.33333333e-01]),
  array([  3.33333333e-01,   3.33333333e-01,   2.77555756e-17,
           3.33333333e-01]))]
```

There is some information about this here: https://nashpy.readthedocs.io/en/v0.0.15/reference/degenerate-games.html
